In [19]:
import pandas as pd
import numpy as np
import yfinance as yf

In [20]:
companies = ["tsla", "aapl", "mcd", "hd"]

In [26]:
tsla_bal = yf.Ticker('tsla')
tsla_bal_data = tsla_bal.balance_sheet.to_dict()

In [27]:
tsla_bal_df = pd.DataFrame.from_dict(tsla_bal_data, orient='index')

In [33]:
tsla_bal_df = tsla_bal_df.transpose()

In [34]:
tsla_bal_df

,Ordinary Shares Number,Share Issued,Total Debt,Tangible Book Value,Invested Capital,Working Capital,Net Tangible Assets,Capital Lease Obligations,Common Stock Equity,Total Capitalization,...,Inventory,Other Inventories,Finished Goods,Work In Process,Raw Materials,Receivables,Accounts Receivable,Cash Cash Equivalents And Short Term Investments,Other Short Term Investments,Cash And Cash Equivalents
2022-12-31,3.164000e+09,3.164000e+09,5.748000e+09,4.411100e+10,4.674900e+10,1.420800e+10,4.411100e+10,3.703000e+09,4.470400e+10,4.573300e+10,...,1.283900e+10,842000000.0,3.475000e+09,2.385000e+09,6.137000e+09,2.952000e+09,2.952000e+09,2.218500e+10,5.932000e+09,1.625300e+10
2021-12-31,3.099000e+09,3.099000e+09,8.873000e+09,2.847200e+10,3.553100e+10,7.395000e+09,2.847200e+10,3.531000e+09,3.018900e+10,3.444300e+10,...,5.757000e+09,575000000.0,1.277000e+09,1.089000e+09,2.816000e+09,1.913000e+09,1.913000e+09,1.770700e+10,1.310000e+08,1.757600e+10
2020-12-31,2.880000e+09,2.880000e+09,1.327900e+10,2.170500e+10,3.249600e+10,1.246900e+10,2.170500e+10,3.008000e+09,2.222500e+10,3.073800e+10,...,4.101000e+09,434000000.0,1.666000e+09,4.930000e+08,1.508000e+09,1.886000e+09,1.886000e+09,1.938400e+10,0.000000e+00,1.938400e+10

In [35]:
mcd_bal = yf.Ticker('mcd')
mcd_bal_data = mcd_bal.balance_sheet.to_dict()

In [36]:
mcd_bal_df = pd.DataFrame.from_dict(mcd_bal_data, orient='index')

In [39]:
mcd_bal_df = mcd_bal_df.transpose()

In [40]:
mcd_bal_df

,Treasury Shares Number,Ordinary Shares Number,Share Issued,Net Debt,Total Debt,Tangible Book Value,Invested Capital,Working Capital,Net Tangible Assets,Capital Lease Obligations,...,Land And Improvements,Properties,Current Assets,Other Current Assets,Prepaid Assets,Inventory,Receivables,Accounts Receivable,Cash Cash Equivalents And Short Term Investments,Cash And Cash Equivalents
2022-12-31,929300000.0,731300000.0,1.660600e+09,3.331970e+10,4.869900e+10,-8.903800e+09,2.990010e+10,1.622100e+09,-8.903800e+09,1.279550e+10,...,6.686300e+09,0.0,5.424200e+09,673400000.0,NaN,52000000.0,2.115000e+09,2.115000e+09,2.583800e+09,2.583800e+09
2021-12-31,915800000.0,744800000.0,1.660600e+09,3.091350e+10,4.934910e+10,-7.383500e+09,3.102170e+10,3.128500e+09,-7.383500e+09,1.372640e+10,...,6.487600e+09,0.0,7.148500e+09,511300000.0,511300000.0,55600000.0,1.872400e+09,1.872400e+09,4.709200e+09,4.709200e+09
2020-12-31,915200000.0,745400000.0,1.660600e+09,3.399130e+10,5.146320e+10,-1.059800e+10,2.961550e+10,6.200000e+07,-1.059800e+10,1.402280e+10,...,6.349100e+09,0.0,6.243200e+09,632700000.0,632700000.0,51100000.0,2.110300e+09,2.110300e+09,3.449100e+09,3.449100e+09

In [41]:
hd_bal = yf.Ticker('hd')
hd_bal_data = hd_bal.balance_sheet.to_dict()

In [42]:
hd_bal_df = pd.DataFrame.from_dict(hd_bal_data, orient='index')

In [45]:
hd_bal_df = hd_bal_df.transpose()

In [46]:
hd_bal_df

,Treasury Shares Number,Ordinary Shares Number,Share Issued,Net Debt,Total Debt,Tangible Book Value,Invested Capital,Working Capital,Net Tangible Assets,Capital Lease Obligations,...,Properties,Current Assets,Other Current Assets,Inventory,Finished Goods,Receivables,Other Receivables,Accounts Receivable,Cash Cash Equivalents And Short Term Investments,Cash And Cash Equivalents
2023-01-31,778000000.0,1.016000e+09,1.794000e+09,4.043600e+10,5.036400e+10,-9.205000e+09,4.475500e+10,9.361000e+09,-9.205000e+09,7.171000e+09,...,0.0,3.247100e+10,1.511000e+09,2.488600e+10,2.488600e+10,3.317000e+09,495000000.0,2.822000e+09,2.757000e+09,2.757000e+09
2022-01-31,757000000.0,1.035000e+09,1.792000e+09,3.774300e+10,4.626900e+10,-1.264800e+10,3.839000e+10,3.620000e+08,-1.264800e+10,6.183000e+09,...,0.0,2.905500e+10,1.218000e+09,2.206800e+10,2.206800e+10,3.426000e+09,525000000.0,2.901000e+09,2.343000e+09,2.343000e+09
2021-01-31,712000000.0,1.077000e+09,1.789000e+09,2.934300e+10,4.342200e+10,-3.827000e+09,4.053700e+10,5.311000e+09,-3.827000e+09,6.184000e+09,...,0.0,2.847700e+10,9.630000e+08,1.662700e+10,1.662700e+10,2.992000e+09,442000000.0,2.550000e+09,7.895000e+09,7.895000e+09
2020-01-31,709000000.0,1.077000e+09,1.786000e+09,2.935000e+10,3.737700e+10,-5.370000e+09,2.836700e+10,1.435000e+09,-5.370000e+09,5.894000e+09,...,0.0,1.981000e+10,1.040000e+09,1.453100e+10,1.453100e+10,2.106000e+09,368000000.0,1.738000e+09,2.133000e+09,2.133000e+09

In [47]:
aapl_bal = yf.Ticker('aapl')
aapl_bal_data = aapl_bal.balance_sheet.to_dict()

In [48]:
aapl_bal_df = pd.DataFrame.from_dict(aapl_bal_data, orient='index')

In [51]:
aapl_bal_df = aapl_bal_df.transpose()

In [52]:
aapl_bal_df

,Treasury Shares Number,Ordinary Shares Number,Share Issued,Net Debt,Total Debt,Tangible Book Value,Invested Capital,Working Capital,Net Tangible Assets,Common Stock Equity,...,Other Current Assets,Inventory,Receivables,Other Receivables,Accounts Receivable,Cash Cash Equivalents And Short Term Investments,Other Short Term Investments,Cash And Cash Equivalents,Cash Equivalents,Cash Financial
2023-09-30,0.0,1.555006e+10,1.555006e+10,8.112300e+10,1.110880e+11,6.214600e+10,1.732340e+11,-1.742000e+09,6.214600e+10,6.214600e+10,...,1.469500e+10,6.331000e+09,6.098500e+10,3.147700e+10,2.950800e+10,6.155500e+10,3.159000e+10,2.996500e+10,1.606000e+09,2.835900e+10
2022-09-30,NaN,1.594342e+10,1.594342e+10,9.642300e+10,1.200690e+11,5.067200e+10,1.707410e+11,-1.857700e+10,5.067200e+10,5.067200e+10,...,2.122300e+10,4.946000e+09,6.093200e+10,3.274800e+10,2.818400e+10,4.830400e+10,2.465800e+10,2.364600e+10,5.100000e+09,1.854600e+10
2021-09-30,NaN,1.642679e+10,1.642679e+10,8.977900e+10,1.247190e+11,6.309000e+10,1.878090e+11,9.355000e+09,6.309000e+10,6.309000e+10,...,1.411100e+10,6.580000e+09,5.150600e+10,2.522800e+10,2.627800e+10,6.263900e+10,2.769900e+10,3.494000e+10,1.763500e+10,1.730500e+10
2020-09-30,NaN,1.697676e+10,1.697676e+10,7.442000e+10,1.124360e+11,6.533900e+10,1.777750e+11,3.832100e+10,6.533900e+10,6.533900e+10,...,1.126400e+10,4.061000e+09,3.744500e+10,2.132500e+10,1.612000e+10,9.094300e+10,5.292700e+10,3.801600e+10,2.024300e+10,1.777300e+10